### ISSUE TITLE
Add .DS_Store to gitignore

### ISSUE THREAD

**Issue by Udit8348** [VEX-Robotics/VAIC_20_21#5]
## Background
What is a [`.DS_Store`](https://en.wikipedia.org/wiki/.DS_Store) file?
This metadata file is user specific so it is good practice to gitignore this file type and keep it local.

## Suggested Changes
1) Add  `.DS_Store` and `**/.DS_Store` to `VAIC_20_21/ai_demo/.gitignore`
2) Delete `.DS_Store` file from `VAIC_20_21/ai_demo`, `VAIC_20_21/ai_demo/include`, and `VAIC_20_21/ai_demo/src` 
3) Stop tracking the file in git with `git rm --cache **/.DS_Store`

**Comment by VEX-Robotics** [comment]
Thanks for catching that. These files have been removed.
